config_data:
  dataset: LUHACombined
  task: all_individual
  transcript_version: google
  split: full
config_model:
  batch_size: 2
  classifier_proj_size: 512
  cv_splits: 1
  learning_rate: 0.0001
  learning_rate_lora: 0.002184523034398742
  lora_dropout: 0.0
  lora_modules: attention_full
  lora_r: 8
  max_audio_length_seconds: 30
  num_train_epochs: 30
  target_variable: composite_language
  use_lora: true
  wavlm_model_name: microsoft/wavlm-base
  use_external_features: false
debug: false
model: WavLM

# also calculate features
data_transformers:
- Audio Features
- Demographic Features
- Task Features
data_preprocessors:
- Outlier Removal and Imputation
- Feature Standardizer
config_audio_features:
  feature_version: reduced
config_linguistic_features:
  feature_version: reduced
config_demographic_features:
  selected_features: ["age", "gender_unified", "education_binary", "country", "socioeconomic"]
