target_variable: composite_language

results_dir_text: /home/ubuntu/methlab/Students/Jonathan/results/runs_luha_cluster/2026_kw22/20260528_1632_deberta_kw38_v1_all_individual_unused_features_wave1_cohortA_hlki
results_dir_audio: /home/ubuntu/methlab/Students/Jonathan/results/runs_luha_cluster/2026_kw22/20260528_1542_wavlm_kw36b_language_all_individual_with_unused_features_wave1_cohortA_umqj

full_results_dir_text: /home/ubuntu/methlab/Students/Jonathan/results/runs_luha_cluster/2026_kw22/20260528_1950_deberta_kw38_v1_all_individual_unused_features_test_on_cohortB_fmst
full_results_dir_audio: /home/ubuntu/methlab/Students/Jonathan/results/runs_luha_cluster/2026_kw22/20260528_1532_wavlm_kw36b_language_all_individual_with_unused_features_test_on_cohortB_loso

n_runs: 1000